#!/usr/bin/env bash

#####################################
#                                   #
#  @author      : 00xWolf           #
#    GitHub    : @mmsaeed509       #
#    Developer : Mahmoud Mohamed   #
#  﫥  Copyright : Exodia OS         #
#                                   #
#####################################

I3_DIR="$HOME/.config/i3"
NOTIFY_ICON="/usr/share/icons/dunst/themes.png"
THEME_NAME=$(grep -Po 'exodiaTheme\s*=\s*\K.*' ${I3_DIR}/exodia.conf)
PREVIEW_IMG="${I3_DIR}/themes/${THEME_NAME}/preview.png"
THEME_CONFIG="${I3_DIR}/themes/${THEME_NAME}/theme.conf"
EXODIA_CONFIG_FILE="${I3_DIR}/exodia.conf"
CONFIG_DIR="$HOME/.config"

# Get Theme config #
BACKGROUND=$(grep '^background\s*=' "${THEME_CONFIG}" | cut -d '=' -f2 | tr -d ' ')
THEME=$(grep '^theme\s*=' "${THEME_CONFIG}" | cut -d '=' -f2 | tr -d ' ')
ICONS=$(grep '^icons\s*=' "${THEME_CONFIG}" | cut -d '=' -f2 | tr -d ' ')
CURSOR=$(grep '^cursor\s*=' "${THEME_CONFIG}" | cut -d '=' -f2 | tr -d ' ')
RGB_KEYBOARD=$(grep '^RGB-keyboard\s*=' "${THEME_CONFIG}" | cut -d '=' -f2 | tr -d ' ')
PICOM=$(grep '^picom\s*=' "${THEME_CONFIG}" | cut -d '=' -f2 | tr -d ' ')

# Notify the user about applying the theme #
dunstify -i "${NOTIFY_ICON}" "[*] Applying 
${THEME_NAME} Theme!"

# --- writing the new values to the config file `exodia.conf` and updating the config --- #

# Updating Background #
dunstify -i "" "[+] Updating Background"
sed -i "s#background = .*#background = ${BACKGROUND}#" ${EXODIA_CONFIG_FILE}


# Updating Color Schemes #
dunstify -i "" "[+] Updating Color Schemes"
sed -i "s#color-scheme = .*#color-scheme = ${THEME_NAME}#" ${EXODIA_CONFIG_FILE}


# set gtk theme, icons and cursor #
dunstify -i "" "[+] Setting gtk theme, icons and cursor"
sed -i "s#theme = .*#theme = ${THEME}#" ${EXODIA_CONFIG_FILE}
sed -i "s#icons = .*#icons = ${ICONS}#" ${EXODIA_CONFIG_FILE}
sed -i "s#cursor = .*#cursor = ${CURSOR}#" ${EXODIA_CONFIG_FILE}

if [[ `pidof xsettingsd` ]];
    
    then
        
        # Update Theme for `xsettingsd` #
        sed -i -e "s|Net/ThemeName .*|Net/ThemeName \"$(grep -oP 'theme = \K.*' "${EXODIA_CONFIG_FILE}")\"|g" ${I3_DIR}/xsettingsd

		# Update Icons for `xsettingsd` #
		sed -i -e "s|Net/IconThemeName .*|Net/IconThemeName \"$(grep -oP 'icons = \K.*' "${EXODIA_CONFIG_FILE}")\"|g" ${I3_DIR}/xsettingsd

		# Update Cursor for `xsettingsd` #
		sed -i -e "s|Gtk/CursorThemeName .*|Gtk/CursorThemeName \"$(grep -oP 'cursor = \K.*' "${EXODIA_CONFIG_FILE}")\"|g" ${I3_DIR}/xsettingsd
		sed -i -e "s|Inherits=.*|Inherits=$(grep -oP 'cursor = \K.*' "${EXODIA_CONFIG_FILE}")|g" ${HOME}/.icons/default/index.theme

else

        # Update Theme for `gtk-2` #
		sed -i -e "s/gtk-theme-name=.*/gtk-theme-name=\"$(grep -oP 'theme = \K.*' "${EXODIA_CONFIG_FILE}")\"/g" ${HOME}/.gtkrc-2.0
		# Update Icons for `gtk-2` #
		sed -i -e "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=\"$(grep -oP 'icons = \K.*' "${EXODIA_CONFIG_FILE}")\"/g" ${HOME}/.gtkrc-2.0
		# Update Cursor for `gtk-2` #
		sed -i -e "s/gtk-cursor-theme-name=.*/gtk-cursor-theme-name=\"$(grep -oP 'cursor = \K.*' "${EXODIA_CONFIG_FILE}")\"/g" ${HOME}/.gtkrc-2.0
		
		# Update Theme for `gtk-3` #
		sed -i -e "s/gtk-theme-name=.*/gtk-theme-name=$(grep -oP 'theme = \K.*' "${EXODIA_CONFIG_FILE}")/g" ${CONFIG_DIR}/gtk-3.0/settings.ini
		# Update Icons for `gtk-3` #
		sed -i -e "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=$(grep -oP 'icons = \K.*' "${EXODIA_CONFIG_FILE}")/g" ${CONFIG_DIR}/gtk-3.0/settings.ini
		# Update Cursor for `gtk-3` #
		sed -i -e "s/gtk-cursor-theme-name=.*/gtk-cursor-theme-name=$(grep -oP 'cursor = \K.*' "${EXODIA_CONFIG_FILE}")/g" ${CONFIG_DIR}/gtk-3.0/settings.ini
		# Update Cursor for `gtk-3` #
		sed -i -e "s/cursor_theme_name=.*/cursor_theme_name=$(grep -oP 'cursor = \K.*' "${EXODIA_CONFIG_FILE}")/g" ${CONFIG_DIR}/gtk-3.0/settings.ini

fi

# Update i3 settings #
dunstify -i "" "[+] Updating i3 settings"

# Setting polybar theme #
dunstify -i "" "[+] Setting polybar theme"
pkill polybar
sed -i "s#polybar = .*#polybar = ${THEME_NAME}#" ${EXODIA_CONFIG_FILE}

# ----- Apply RGB Colors For Keyboard ----- #
dunstify -i "" "[+] Changing RGB colors For the Keyboard"
sed -i "s#RGB-keyboard = .*#RGB-keyboard = ${RGB_KEYBOARD}#" ${EXODIA_CONFIG_FILE}

# ----- Updating picom config ----- #
dunstify -i "" "[+] Updating picom config"
sed -i "s#picom = .*#picom = ${PICOM}#" ${EXODIA_CONFIG_FILE}

# ----- set background for betterlockscreen based on the selected theme ----- #
STATUS=$(grep -Po 'change-betterlockscreen\s*=\s*\K.*' ${EXODIA_CONFIG_FILE})
if [[ ${STATUS} == "true" ]];
    
    then

        dunstify -i "" "[+] Updating betterlockscreen Background"
        betterlockscreen -u ${BACKGROUND}

fi

# Updating i3 config #
dunstify -i "" "[+] Updating i3 config"
cat "$I3_DIR/themes/$THEME_NAME/config" > ${I3_DIR}/config

# ----- reload config ----- #
dunstify -i "" "[+] Reload The Configurations"
i3-msg restart

# Notify the user about successfully applying the theme #
dunstify -i "${PREVIEW_IMG}" " ${THEME_NAME} Theme 
Applied Successfully [✔]"
