#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="/usr/share/archcraft/dwm"
RASI="$DIR/theme/rofi/filebrowser.rasi"

# Run
rofi \
	-show filebrowser -theme ${RASI}
