#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="~/.config/i3/"
RASI="$DIR/theme/rofi/windows.rasi"

# Run
rofi \
	-show windowcd \
	-theme ${RASI}
